name: Count Lines of Code

on: [push, pull_request]

jobs:
  count_loc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Count LOC
        run: find . -name '*.php' -o -name '*.html' -o -name '*.css' -o -name '*.js' | xargs wc -l

